# Positions are in meters from back left foot. ENU convention
# Pose is xyzrpy with rpy in radians

# Visual model for gazebo and rviz
mesh: package://riptide_descriptions/meshes/Puddles.dae
mass: 39.825 # kg
base_link: [0.397, -0.205, 0.17] 
com: [0.397, -0.205, 0.17]
inertia: [1.32, 2.84, 3.65]

dvl:
  topic: dvl
  rate: 8 # Hz
  sigma: 0.001 # Stdev in m/s. Used by gazebo
  pose: [0.33, 0, 0.44, 0, 0, 0]

depth:
  topic: depth/pressure
  rate: 20 # Hz
  sigma: 20.0 # Stdev in kPa. Used by gazebo
  pose: [0.533, -0.219, 0.118, 0, 0, 0]

imu:
  topic: imu/data
  # Noise modeling is weird and is hard coded in gazebo with some numbers.
  # Is not modeled from real IMU
  rate: 100 #Hz
  pose: [0.71, -0.19, 0.33, 0, 0, 3.14159]

cameras: [
  {
    type: stereo,
    name: stereo,
    rate: 30,
    hfov: 1.8,
    width: 644,
    height: 482,
    stddev: 0.02,
    baseline: 0.1,
    pose: [0.781, -0.1326, 0.2466, 0, 0, 0]
  },
  {
    type: mono,
    name: downward,
    rate: 30,
    hfov: 1.8,
    width: 644,
    height: 482,
    stddev: 0.02,
    pose: [0.470, -0.181, 0.127, 0, 1.5708, 0]
  }
]