t200:
  limits:
    thrust:
      min: -50
      max: 50
  link:
    mesh_properties:
      visual: package://common_robot_description/meshes/propeller.dae
    inertial:
      mass: 0.005
      com: 0 0 0
      inertia:
        ixx: 0.000000017
        ixy: 0.0
        ixz: 0.0
        iyy: 0.000000017
        iyz: 0.0
        izz: 0.000000017
  gazebo:
    dynamics: ZeroOrder
    thrust_conversion:
      type: Basic
      constant: -0.005 # The negative sign is for visual purposes so the propeller spins correctly