camera:
  stereo:
    parent_link: base_link
    update_rate: 30
    hfov: 1.5125
    width: 644
    height: 482
    stddev: 0.02
    origin:
      xyz: 0.781 -0.1326 0.2466
      rpy: 0 0 0


  downward:
    topic_suffix: downward
    parent_link: base_link
    update_rate: 30
    hfov: 1.5125
    width: 644
    height: 482
    stddev: 0.02
    scale: 1.0
    origin:
      xyz: 0.470 -0.181 0.127
      rpy: 0 1.57079 0

pressure:
  pressure:
    topic_suffix: downward
    parent_link: base_link
    update_rate: 20
    noise_sigma: 0
    noise_amplitude: 0.03 # [kPa]
    origin:
      xyz: .533 -0.219 0.118
      rpy: 0 0 0

imu:
  imu:
    topic_suffix: ""
    parent_link: base_link
    reference_frame: world # Do NOT use world_ned - the sensor output is not correct
    origin:
      xyz: 0.71 -0.19 0.33
      rpy: 0 0 0

dvl:
  dvl:
    topic_suffix: ""
    parent_link: base_link
    reference_frame: world # Use world_ned
    update_rate: 8
    noise_sigma: 0
    noise_amplitude: 0.01 # Gets applied to velocity output
    origin:
      xyz: -0.081297 -0.081297 -.2
      rpy: 0 1.57079 0
