base_link:
  link:
    name: base_link
    mesh_properties:
      visual: package://maelstrom_description/model/meshes/maelstromColored.dae
      collision: package://maelstrom_description/model/meshes/collision.stl
    dummy_link:
      name: base_inertia
    dummy_joint:
      name: base_joint
    inertial:
      mass: 40.85
      com: 0 0 0
      inertia:
        ixx: 1.32
        ixy: 0.0
        ixz: 0.0
        iyy: 2.84
        iyz: 0.0
        izz: 3.65
    hydro:
      box: # Bounding Box
        length: 0.89
        width: 0.5
        height: 0.33
      cob: 0 0 0 # Relative to base_link origin
      volume: 0.0428
      damping:
        linear: -11.7391 -20 -31.8678 -25 -44.9085 -5
        quadratic: 0 0 0 0 0 0
      added_mass: >
        0 0 0 0 0 0
        0 0 0 0 0 0
        0 0 0 0 0 0 
        0 0 0 0 0 0
        0 0 0 0 0 0
        0 0 0 0 0 0
